### PR TITLE
Added empty list messages

### PR DESCRIPTION
**Pull request by PJSosnowski**
Added empty list messages where it was needed, as mentioned in #37 

> Please add the empty list warning to the rest of the lists in Motech in the second PR.

for proper working motech/motech#676 is required

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
@PJSosnowski It looks good, what about the messages list in Admin Messages and bundles list in Admin Manage modules?

**Comment by PJSosnowski** [comment]
@jredlarski messages list in Admin Messages already has this message, should I change it to be in the same manner?

**Comment by jredlarski** [comment]
@PJSosnowski Yes, it should look the same across all the lists in the UI

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
@PJSosnowski Please apply changes for the names of the variables which should be changed in [motech/motech#676](https://github.com/motech/motech/pull/676)

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
test this please

**Pull request merged**
