### PR TITLE
MOTECH-2665 Migrate admin settings page fixes after comments

### PR DESCRIPTION
**Pull request by ghost**
settingspage1
settingspage3
settingspage2
Please verify if that looks good.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
@pgesek Can you take a look at the screenshots and let us know if this looks good to you now?

**Comment by sebbrudzinski** [comment]
I'll merge it in then.

**Pull request merged**
