### PR TITLE
Replaces SC5 with JSDoc

### PR DESCRIPTION
**Pull request by nickdotreid**
Replaced KSS styleguide generator with JSDoc generator because most
meaningful code is in JS, which is what needs most documentation.
Created stubs for tutorial entries that will need to be added.

I'd like to more sample content into this PR before merging, but I thought I would share the direction.

You can build the documentation by running 'gulp:docs' and serve it locally with 'gulp serve:docs'

### CODE REVIEW

**Comment by nickdotreid** [comment]
@jredlarski I think this PR is ready to be merged...

Can you try to generate and look through the start of the documentation, and let me know if something isn't clear enough or should be changed

The instructions for creating and updating the documentation is on the README.md page

**Comment by jredlarski** [comment]
@nickdotreid Please resolve conflicts which appeared after merging [Loading Modal PR](https://github.com/motech/motech-ui/pull/18)

Also I've noticed that templates for motech-list, motech-list-item and input-map do not load.

**Comment by nickdotreid** [comment]
@jredlarski I've resolved the merge conflict, but I don't see the errors for templates not loading (and am unclear if you mean they don't load in the app or the documentation)

**Comment by jredlarski** [comment]
@nickdotreid Great! Sorry, I should have specified it more clearly. They do not load in documentation and I get 404 error in browser, but I can see that there is no file in build/docs/templates directory so it isn't anything strange. Apart from that I'm totally ok with your PR

**Comment by nickdotreid** [comment]
@jredlarski oddly enough, I never thought to click on that link...

**Comment by nickdotreid** [comment]
@jredlarski I updated the template that is being used, apparently that 'templates' path was not being used...

As a sidenote, I find it infuriating that many of the JS Documenting tools almost require you to build a separate website

**Comment by jredlarski** [comment]
@nickdotreid Ok, now everything seems fine. I'm merging this PR

In case of JS Documenting tools, unfortunately I'm not aware if there is a better way for creating documentation that we need...

**Pull request merged**
