### PR TITLE
MOTECH-2667 Migrate admin server log to MOTECH-UI

### PR DESCRIPTION
**Pull request by wstrzelczyk**
This pull request is adding Admin Server Log section to the MOTECH UI.

### CODE REVIEW

**Comment by nickdotreid** [comment]
@wstrzelczyk The only notes I have is expose a link in the admin navigation to the logs page, and squash down your commits — and I'll merge it

**Comment by sebbrudzinski** [comment]
@nickdotreid Just a side note - it is possible to squash commits during pull request merge (might need to be enabled in repository settings - it is enabled on motech and modules repos)

**Comment by nickdotreid** [comment]
@sebbrudzinski -- I didn't know that was a think... I'll go figure out how to do that

**Comment by sebbrudzinski** [comment]
@nickdotreid https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by wstrzelczyk** [comment]
@nickdotreid The admin navigation to the logs page is and was on proper place, can you explain me what you mean?

**Comment by nickdotreid** [comment]
@wstrzelczyk, you are right, the link is now in the right place -- I either missed it or am slightly crazy (or maybe you snuck it in on a commit somewhere XP  )

I'll merge now

**Pull request merged**
